insert into frage (frage, richtig, falsch1, falsch2, falsch3, bild, erklaerung) Values
('Wie heißt das "Herz" des Berges Erebor in Tolkiens "Hobbit"', 'Arkenstein', 'Londrondur', 'Endroil', 'Thorinader', null, 'Der Arkenstein, auch das Königsjuwel genannt, war der schönste und prächtigste Edelstein in Mittelerde, von den Silmaril einmal abgesehen und der größte Schatz der Könige unter dem Berg.')
('Wie heißt der 1871 geborene Dichter und Schriftsteller Morgenstern mit Vornamen?', 'Christian', 'David', 'Ansgar', 'Karl-Heinz', null, 'Christian Otto Josef Wolfgang Morgenstern (* 6. Mai 1871 in München; † 31. März 1914 in Untermais, Tirol, Österreich-Ungarn) war ein deutscher Dichter, Schriftsteller und Übersetzer. Besondere Bekanntheit erreichte seine komische Lyrik, die jedoch nur einen Teil seines Werkes ausmacht.'),
('Wie heißt der Affe in den Geschichten von "Pippi Langstrumpf"', 'Herr Nielsson', 'Herr Larsson', 'Großer Onkel', 'Kleiner Onkel', null, 'Pippi Langstrumpf ist die zentrale Figur einer dreibändigen schwedischen Kinderbuch-Reihe von Astrid Lindgren. Pippi Langstrumpf lebt zusammen mit ihrer Meerkatze (im Film: Totenkopfäffchen) Herr Nilsson und ihrem Apfelschimmel (im Film heißt das Pferd „Kleiner Onkel“, in der Villa Kunterbunt (schwedisch: Villa Villekulla) am Rande einer kleinen, namenlosen Stadt.'),
('Wie heißt der Vergnügungspark in Plailly nördlich von Paris, der Asterix und seinen Galliern gewidmet ist?', 'Parc Astérix', 'Gauleparc', 'Parcerix', 'Disneyland Resort', null, 'Der Parc Astérix ist ein im Jahr 1989 in der 30 km nördlich von Paris gelegenen Gemeinde Plailly eröffneter Freizeitpark, dem eine Hotelanlage angeschlossen ist. Dieser der Welt des Comichelden Asterix geweihte Themenpark nimmt mit etwa 1,8 Millionen Besuchern den vierten Rang unter den besucherstärksten Freizeitparks in Frankreich ein.'),
('Wer gehört NICHT zu den "Watchmen"', 'Kick-Ass', 'Dr. Manhatten', 'Nhite Owl', 'Rorschach', null, 'Watchmen ist eine 1986/87 erschienene Graphic Novel von Alan Moore (Text) und Dave Gibbons (Zeichnungen). Kick-Ass ist ein britisch-US-amerikanischer Spielfilm aus dem Jahr 2010 von Matthew Vaughn, der auf Mark Millars gleichnamigem Comic basiert. Insofern gehört Kick-Ass nicht zu den Watchmen'),
('Wie heißt der Schöpfer von "Goofy"', 'Art Babbit', 'Don Rosa', 'Carl Barks', 'Walt Disney', null, 'Goofy (adj. engl. für „albern“, „doof“) wurde von Art Babbitt (Arthur Harold Babitsky, 1907–1992) erdacht und ist der treue Freund von Micky Maus. Die Comic-Figur gehört, wie auch Donald Duck, mit zu den ersten Disneyfiguren. Ursprünglich hieß er Dippy Dawg (verdrehter Hund), 1939 wurde die Figur dann aber in Goofy umbenannt.'),
('Welche Pflanze verbirgt sich hinter dem Namen Nymphaea?', 'Seerose', 'Vogelmiere', 'Birke', 'Efeu', null, 'Die Seerosen (Nymphaea) sind eine Pflanzengattung in der Familie der Seerosengewächse (Nymphaeaceae). Die weltweit verbreitete Gattung umfasst etwa fünfzig Arten.'),
('Was ist ein "Gestreifter Marlin"?', 'Ein Fisch', 'Eine Koralle', 'Ein Krake', 'Ein Seeigel', null, 'Der indopazifische Gestreifte Marlin (Kajikia audax) gehört zur Ordnung der Schwertfischartigen. Er bildet – darin vergleichbar mit dem Fächerfisch und mit seiner atlantischen Schwesterart Weißer Marlin – ein weltweit in wärmeren Meeren verbreitetes Taxon von schnellen, epipelagischen Spitzenprädatoren, die zugleich für die Sportfischerei von größter Bedeutung sind.'),
('Welches der folgenden Produkte wird von der Firma Asus entwickelt', 'Laptop', 'Schreibtischlampe', 'Bürostuhl', 'Klimaanlage', null, 'ASUSTeK Computer Inc. (Asus) ist ein großer taiwanischer Hersteller von Computer-Hardware mit Sitz in Taipeh. Das Unternehmen ist allgemein unter dem Markennamen Asus bekannt. Asus produziert hauptsächlich Notebooks und PCs im Businessbereich und Leistungscomputerbereich (zum Beispiel Firmennetzwerke).'),
('Was produzierte John Curtis Jackson 1848 erfolgreich aus Fichtenharz', 'Kaugummi', 'Klebstoff', 'Fahrradschlauch', 'Schuhsohle', null, 'Der oder das Kaugummi ist eine leicht verformbare, meist süß, manchmal auch scharf (Minze) oder sauer schmeckende Masse in einer Portionsverpackung, auf der oft einige Stunden lang gekaut werden kann, ohne dass sie zerfällt. Der erste Kaugummifabrikant war der US-Amerikaner John Curtis Jackson. Er verwendete ein indianisches Rezept mit Fichtenharz als Grundstoff und Bienenwachs. 1848 begann er mit der Produktion seines Kaugummis und war auf Anhieb erfolgreich.'),
('Aus welchem Land kommt die Spielzeugmarke Lego', 'Dänemark', 'Niederlande', 'Belgien', 'Deutschland', null, 'Die Lego A/S (auch The LEGO Group, Eigenschreibweise: LEGO) ist ein dänisches Unternehmen und größter Spielzeughersteller der Welt, das durch die mittlerweile als Spielzeugklassiker geltenden Legosteine bekannt wurde. Das Wort Lego leitet sich von dänisch leg godt „spiel gut“ ab.'),
('Welche britische Zeitung hatte 1989 die umstrittene und viel diskutierte Schlagzeile "THE TRUTH" auf der Titelseite?', 'The Sun', 'The Evening Standard', 'The Daily Mirror', 'The Times', null, 'Unter dem Titel „The Truth“ (Die Wahrheit) wurde in der Boulevardzeitung The Sun vier Tage nach der Hillsborough-Katastrophe wahrheitswidrig behauptet, Liverpool-Fans hätten Rettungsversuche der Polizei behindert und Betroffene beraubt. Die Hillsborough-Katastrophe war ein schweres Zuschauerunglück mit 96 Toten und 766 Verletzten am 15. April 1989 im Hillsborough Stadium in Sheffield. Sie ereignete sich während des Halbfinalspiels um den FA Cup zwischen dem FC Liverpool und Nottingham Forest.'),
('Wie viele Goldmedaillen gewann Georg Hackl bei der Wok-WM', '9', '11', '5', '2', null, 'Hackl nahm bisher an 12 Weltmeisterschaften der Funsportart Wok-Fahren teil. Im Einzel-Wok wurde er neunmal Weltmeister (2004, 2005, 2007–2013) und dreimal Vizeweltmeister (2006, 2014 und 2015), im Vierer-Wok erreichte er einmal den zweiten Platz (2006). Damit ist Hackl der mit Abstand erfolgreichste Wok-Fahrer.'),
('In welchem Zeitraum waren Bruce Willis und Demi Moore verheiratet?', '1987-2000', '2000-2005', '1985-1996', '1999-2005', null, 'Am 21. November 1987 heiratete sie den Schauspieler Bruce Willis. Das Paar hat drei gemeinsame Töchter. Am 24. Juni 1998 trennten sich Moore und Willis, sie reichten die Scheidung allerdings erst am 18. Oktober 2000 ein, bereits tags darauf war sie rechtskräftig.'),
('Wie heißt das außerirdische Wesen, das in der Serie "Superman" die Herrschaft über die Erde übernehmen will?', 'Brainiac', 'The Joker', 'Morgan Edge', 'Lex Luthor', null, 'Brainiac ist eine Comicfigur, die 1958 von dem US-amerikanischen Science-Fiction-Schriftsteller Otto Binder geschaffen wurde.  In den frühen Superman-Geschichten wurde Brainiac als ein grünhäutiger außerirdischer Wissenschaftler und Eroberer definiert.'),
('Wie heißt die Grunge-Band von Trent Lane aus der Zeichentrickserie "Daria"?', 'Mystic Spiral', 'Malfunkshun', 'L7', 'The Melvins', null, 'Mystic Spiral ist die Band, welche von Trent Lane geleitet wird. Dieser ist der Bruder von Darias Freund Jane. Die Band ist eine alternative rock-grunge Band, wobei Elemente des Heavy Metal enthalten sind.'),
('Welche Serie handelt von einem Jungen und seinem Spielzeugtieger?', 'Calvin und Hobbes', 'Draußen auf der Weide', 'Marsupilami', 'Beetle Bailey', null, 'Calvin und Hobbes ist ein Comicstrip von Bill Watterson. Die beiden Hauptfiguren des Strips sind Calvin, ein sechsjähriger Junge, der mit seinen Eltern in einem Vorort einer nie benannten amerikanischen Stadt lebt, und sein (Stoff-)Tiger Hobbes.'),
('Wie heißt die im Jahre 2006 von Nintendo veröffentlichte Spiele-Konsole, die mit ihren optischen Kontrollen die Videospiele revolutioniert hat?', 'Wii', 'Gamecube', 'Playstation 3', 'XBOX 360', null, 'Die Wii ist eine 2006 von Nintendo veröffentlichte Spielkonsole. Ihr wesentliches Merkmal ist ein Controller, der herkömmlichen Fernbedienungen ähnelt, aber über eingebaute Bewegungssensoren verfügt. Diese registrieren die Lage und die Bewegungen des Controllers im Raum und setzen sie in entsprechende Bewegungen von Spielfiguren oder -elementen auf dem Bildschirm um.'),
('Was ist KEINE wählbare Rasse in "World of Warcraft"', 'Kreuzritter', 'Orks', 'Menschen', 'Trolle', null, 'Die Völker von World of Warcraft leben in Azeroth und teilen sich in die Allianz (Pandaren, Worgen, Draenai, Zwerge, Gnome, Menschen, Nachtelfen) und in die Horde auf (Pandaren, Goblins, Blutelfen, Orcs, Tauren, Trolle, Untote)'),
('Wer hat das Spiel "Tibia" entwickelt?', 'Cipsoft', 'Mojang', 'Jagex', 'Dice', null, 'Tibia ist eines der ältesten und erfolgreichsten Massen-Mehrspieler-Online-Rollenspiele (Massive Multiplayer Online Role Playing Game, kurz MMORPG) Europas. Tibia wird vom Regensburger Softwareentwickler CipSoft entwickelt und vermarktet. Weltweit spielen mehr als 500.000 aktive Menschen Tibia.'),
('Welcher Stoff ist in Colagetränken üblicherweise enthalten?', 'Kohlendioxid', 'Kohlenmonoxid', 'Colatrioxid', 'Taurin', null, 'Kohlensäure (H2CO3) ist eine anorganische Säure und das Reaktionsprodukt ihres Säureanhydrids Kohlendioxid (CO2) mit Wasser. Da Cola Kohlensäure enthält, enthält sie auch Kohlendioxid'),
('In welcher Einheit wird die Farbe von Bier unterschieden', 'EBC', 'BMI', 'IBM', 'GBM', null, 'Mit der Einheit EBC wird im Europäischen Raum die Farbe (genauer: Die Farbstärke) von Bier und Bierwürze beschrieben. Der von der European Brewery Convention festgelegte Wert bezeichnet, wie viel Licht von Bier eines bestimmten Stammwürzegehalts absorbiert wird'),
('Wie nennt man das Antiteilchen eines Elektrons mit dem Formelzeichen "e+"?', 'Positron', 'Negatron', 'Neutron', 'Proton', null, 'Das Positron (Kunstwort aus positive Ladung und Elektron), Formelzeichen e+, ist ein Elementarteilchen aus der Gruppe der Leptonen. Es ist das Antiteilchen des Elektrons, mit dem es bis auf das Vorzeichen der elektrischen Ladung und des magnetischen Moments in allen Eigenschaften übereinstimmt.'),
('Welches Elementsymbol hat Thallium im Periodensystem?', 'Tl', 'Tu', 'Tm', 'Ta', null, 'Thallium ist ein chemisches Element mit dem Elementsymbol Tl und der Ordnungszahl 81. Im Periodensystem steht es in der 3. Hauptgruppe, bzw. der 13. IUPAC-Gruppe, der Borgruppe. Das weiche, graue und dem Blei sehr ähnliche Metall ist äußerst giftig.'),
('Welcher Begriff beschreibt den Zustand, aus dem sich das Universum ausbreitete?', 'Singularität', 'Supernova', 'Megaplanet', 'Roter Zwerg', null, ' Extrapoliert man die Expansion im Rahmen der Allgemeinen Relativitätstheorie immer weiter in die Vergangenheit, gelangt man allerdings an einen unerfreulichen Punkt in den Gleichungen: die Singularität. Hier bricht die Physik zusammen, die Naturgesetze verlieren ihre Gültigkeit und wissenschaftliche Aussagen sind unmöglich, weil Temperatur und Dichte unendlich, Raum und Zeit dagegen null werden.'),
('Welche Wortbedeutung hat der Name Felix?', 'Der Glückliche', 'Der Erhabene', 'Der Geduldsame', 'Der Sparsame', null, 'Felix kommt aus dem Lateinischen (felix, felicis) und bedeutet „vom Glück begünstigt“, „glücklich“, „erfolgreich“, oder „der Glückliche“. Weibliche Versionen des Vornamens sind Felicitas, Felicia und Felizitas. Die italienische Form des Namens ist Felice.'),
('Was verkaufte "Timm Thaler" im gleichnamigen Roman von James Krüss?', 'Sein Lachen', 'Seine Seele', 'Seine Fantasie', 'Sein Augenlicht', null, 'Timm Thaler oder Das verkaufte Lachen ist ein 1962 erschienener Roman des deutschen Autors James Krüss.'),
('Wer ist KEINE Figur in den Geschichten von "Tausendundeiner Nacht?"', 'Der kleine Muck', 'Aladin', 'Sheherazade', 'Sindbad', null, 'Tausendundeine Nacht ist eine Sammlung morgenländischer Erzählungen und zugleich ein Klassiker der Weltliteratur. Typologisch handelt es sich um eine Rahmenerzählung mit Schachtelgeschichten.'),
('Wie hieß die Cape Canaveral Air Force Station zwischen 1964 und 1973?', 'Cape Kenedy Air Force Station', 'Cape Apollo Air Force Station', 'Cape Nixon Air Force Station', 'Cape America Air Force Station', null, ''),
('Wer gründete neben Bill Gates im Jahr 1975 die Firma Microsoft?', 'Paul Allan', 'Paul Snyder', 'James Allan', 'David Packard', null, ''),
('Mit welcher freien und kostenlosen open Source Software kann man Daten, wie zum Beispiel E-Mails verschlüsseln?', 'GNU Privacy Guard', 'Damn Good Privacy', 'ELK Crypto Guard', 'Apple iCrypt', null, ''),
('Wie heißt eine Sauce Béarnaise mit Tomatenmark?o"', 'Choronsauce', 'Tzatziki', 'Rotweinsauce', 'Sauce Hollondaise', null, ''),
('Wie lautet der Name einer grünen Rebsorte?', 'Moscatel', 'Sangiovese', 'Cabernet Sauvignon', 'Pinotage', null, ''),
('Wenn sie in Italien sind und "pranzo" essen, was essen sie dann?', 'Mittagessen', 'Omelett', 'Frühstück', 'Suppe', null, ''),
('Welche deutsche Serienfigur wurde im Februar 2014 erstmals Hauptfigur in einem Kinofilm?', 'Bernd Stromberg', 'Semir Gerkhan', 'Lisa Plenske', 'Mick Brisgau', null, ''),
('Welche Farbe haben die Feinde der roten Gartenzwerge in "Gnomea und Julia"?', 'Blau', 'Gelb', 'Violett', 'Grün', null, ''),
('Was wird in Bayern und Österreich als "Schwammerl" bezeichnet?', 'Pilze', 'Kartoffeln', 'Gurken', 'Tomaten', null, ''),
('Wie lautet das letzte Wort folgenden Werbespruches: "Schönes Haar ist dir gegeben, lass es leben mit... "?', 'Gard', 'Schauma', 'Pantenne', 'Shamtu Shampoo', null, ''),
('Welcher Talkshowmoderator wurde im Jahr 2004 von proSieben wegen des Vorwurfs der Vergewaltigung entlassen?', 'Andreas Türck', 'Peter Imhof', 'Oliver Geissen', 'Jürgen Fliege', null, ''),
('In welchem Jahr wurde der Komiker Mario Barth geboren?', '1972', '1977', '1962', '1967', null, ''),
('Welche Schutzgötter verkehrten in den Häusern der alten Römer?', 'Penaten', '', '', '', null, ''),
('Zentauren sind mythische Mischwesen aus mensch und Tier. Wie sind sie zusammengesetzt?', 'Mensch mit Pferdeleib', 'Mensch mit Vogelkopf', 'Mensch mit Elefantenkopf', 'Mensch mit Stierkopf', null, ''),
('Wann wurden die Zeugen Jehovas in den Vereinigten Staaten gegründet?', '1870er', '1910er', '1830er', '1850er', null, ''),
('Welche biblische Figur ging außer Jesus laut Matthäus-Evangelium ein Stück auf dem Wasser?', 'Petrus', 'Johannes', 'Barnabas', 'Paulus', null, ''),
('Wer wurde in Daniels Buch in der Bibel in den Feuerofen geworfen?', 'Shadrak, Meshak und Aved-Nego', 'Kain und Abel', 'Aaron und Moses', 'David und Goliath', null, ''),
('Welches Unternehmen steckt hinter dem Smartphone Spiel "Fruit Ninja"', 'Halfbrick Studios', 'Donut Games', 'Electronic Arts', 'Rovio Mobile', null, ''),
('Wie lautet eine früher verwendete Bezeichnung für einen Planeten?', 'Wandelstern', 'Formstern', 'Laufstern', 'Schrittstern', null, ''),
('Welcher der folgenden Charaktere kommt nicht in den Sherlock Holmes-Büchern vor?', 'Mr. Walker', 'Mrs. Hudson', 'Proj. James Moriarty', 'Dr. John H. Watson', null, ''),
('Worum geht es in dem Buch "Elf Minuten" (2003) von Paulo Coelho?', 'Prostituierte', 'Prostituierter Mann', 'Kindesmissbrauch', 'Kfz-Diebstahl', null, ''),
('Welche Zeit lief der Jamaikaner Usain Bolt über 200m im olympischen Finale von London 2012?', '19.32s', '17.32s', '18.32s', '16.32s', null, ''),
('Wie heißt das Mafia-Spiel aus dem Jahre 2002, in dem man Tommy Angela im Amerika der 1930er-Jahre spielt?', 'Mafia', 'Mob Wars', 'Dirty Money', 'Grand Theft Auto', null, ''),
('In welcher Kriegsspiel-Serie kommen die Spiele "Black Ops", "Modern Warfare" und "World at War" vor?', 'Call of Duty', 'Killzone', 'Resistance', 'Team Fortress', null, ''),
('Wo lebt die Van-Katze?', 'Türkei', 'Kongo', 'Chile', 'Neuseeland', null, ''),
('Von welchem Tier stammt der klassische Feta-Käse?', 'Schaf', 'Kuh', 'Büffel', 'Gams', null, ''),
('Was sind Piroggen?', 'Gefüllte Teigtaschen', 'Gekochte Schnecken', 'Gedünstete Austern', 'Kleine Schnitzel', null, ''),
('Welche mysteriöse Figur aus dem Buch "Der Herr der Ringe" lebt im alten Wald?', 'Tom Bombadil', 'Bauer Maggot', 'Sheldor', 'Saruman', null, ''),
('Was verursachte den Absturz einer Concorde kurz nach dem Start im Jahr 2000?', 'Metallstück auf der Startbahn', 'Blitzeinschlag', 'Ohnmacht des Piloten', 'Vogelschwarm', null, ''),
('Welcher Discounter geriet im Frühjahr 2008 aufgrund von illegaler Mitarbeiterüberwachungen in die Schlagzeilen?', 'Lidl', 'Aldi', 'Real', 'Penny', null, ''),
('Mit welchem Land ging Singapur nach der Unabhängigkeit von Großrittanien 1963 eine kurze Förderation ein, die 1965 wieder zerbrach?', 'Malaysia', 'Tibet', 'Nepal', 'China', null, ''),
('Warum akzeptierte Karl der Große einen Friedensvertrag mit Widukind?', 'Widukind ließ sich taufen', 'Widukind bestach Karl', 'Widukind wurde ermordet', 'Widukind beging Suizid', null, ''),
('Ein Sohn von Britney Spears heißt Jayden James, aber wie heißt ihr anderer Sohn?', 'Sean Preston', 'Eric Scott', 'Corey Lewis', 'William Joe', null, ''),
('In welchem Jahr wurde "Wer wird Millionär" zum ersten Mal ausgestrahlt?', '1999', '2001', '1997', '2003', null, ''),
('Welche Waffe benutzen Winnetou und Old Shatterhand nicht?', 'Hirschfänger', 'Bärentöter', 'Henrystutzen', 'Silberbüchse', null, ''),
('Was bedeutet deraus dem Hebräischem stammende Begriff "Tohuwabohu"', 'Wüst und leer', 'Unordnung und Chaos', 'Wirrwarr und Chaos', 'Durcheinander und Leere', null, ''),
('Oscar Fingal wurde 1854 in Irland geboren und schrieb "Das Bildnis des Dorian Grey" und "Mister Ernest". Unter welchem Namen ist er auch bekannt?', 'Oscar Wilde', 'Oscar Cleve', 'Oscar Hijuelos', 'Oscar de la Hoya', null, ''),
('Wie heißen die langen Fühler neben der Nase einer Katze?', 'Schnurrhaare', 'Gefühlshaare', 'Nasenhaare', 'Stabhaare', null, ''),
('Welches Tier beschlagnahmte der Münchener Zoll von Justin Bieber im Jahr 2013?', 'Affe', 'Hund', 'Katze', 'Hamster', null, ''),
('Wer moderierte sowohl "Herzblatt", "Das Quiz" als auch "Rette die Millionen"?', 'Jörg Pilawa', 'Guido Cantz', 'Kai Pflaume', 'Rainhard Fendrich', null, ''),
('Dank einer Vielzahl von radioaktiven Datierungsmethoden ist man sich in der Wissenschaft mittlerweile einig, dass die Erde in etwa wie alt ist?', '4,5 Mrd. Jahre', '4.5 Mio. Jahre', '4500 Jahre', '4,5 Bio. Jahre', null, ''),
('Wie viele Kilometer misst die Erde im Durchmesser?', 'ca. 12700', 'ca. 40000', 'ca. 24400', 'ca. 6350', null, ''),
('Wer erlebte seinen 40. Geburtstag?', 'Friedrich Schiller', 'Franz Schubert', 'Vincent van Gogh', 'Wolfgang Amadeus Mozart', null, ''),
('Was ist laut Buddhismus die Wurzel des menschlichen Leidens?', 'Begierde', 'Krankheit', 'Bosheit', 'Stress', null, ''),
('Mohammed war nicht nur ein religiöser sondern auch ein politischer Führer. Welche Stadt eroberte er im Jahre 630 n. Chr.?', 'Mekka', 'Medina', 'Bagdad', 'Kairo', null, '');


Insert into kategorie(name) VALUES
('Natur'),
('Unterhaltung'),
('Medien'),
('Literatur'),
('Wissenschaft und Technik'),
('Sport, Gesundheit und Ernährung'),
('Geschichte'),
('Sonstiges');


Insert into frage_kategorie(frage, kategorie) VALUES
('1', '4'),
('2', '4'),
('3', '4'),
('4', '2'),
('5', '2'),
('6', '2'),
('7', '1'),
('8', '1'),
('9', '5'),
('10', '5'),
('11', '2'),
('12', '3'),
('13', '2'),
('14', '3'),
('15', '2'),
('16', '2'),
('17', '2'),
('18', '3'),
('19', '2'),
('20', '2'),
('21', '6'),
('22', '6'),
('23', '5'),
('24', '5'),
('25', '5'),
('26', '8'),
('27', '4'),
('28', '4'),
('29', '7'),
('30', '8'),
('31', '5'),
('32', '6'),
('33', '6'),
('34', '6'),
('35', '3'),
('36', '3'),
('37', '6'),
('38', '3'),
('39', '3'),
('40', '2'),
('41', '8'),
('42', '8'),
('43', '7'),
('44', '8'),
('45', '8'),
('46', '2'),
('47', '5'),
('48', '4'),
('49', '4'),
('50', '6'),
('51', '2'),
('52', '2'),
('53', '1'),
('54', '6'),
('55', '6'),
('56', '4'),
('57', '8'),
('58', '8'),
('59', '7'),
('60', '7'),
('61', '3'),
('62', '3'),
('63', '4'),
('64', '8'),
('65', '4'),
('66', '1'),
('67', '3'),
('68', '3'),
('69', '5'),
('70', '5'),
('71', '7'),
('72', '8'),
('73', '7');





